DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS department;

DROP SEQUENCE IF EXISTS department_ids;
DROP SEQUENCE IF EXISTS user_ids;
DROP SEQUENCE IF EXISTS subject_ids;
